import React from "react";
import { Route, Switch } from "react-router";

const routes = [
  {
    name: "Home",
    path: "/en",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Home",
    path: "/ar",
    isPrivate: false,
    exact: true,
  },
  {
    name: "ourPrudcts",
    path: "/en/mother-baby-products",
    isPrivate: false,
    exact: true,
  },
  {
    name: "ourPrudcts",
    path: "/ar/mother-baby-products",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Cart",
    path: "/en/cart",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Cart",
    path: "/ar/cart",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Checkout",
    path: "/en/checkout",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Checkout",
    path: "/ar/checkout",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Tracking",
    path: "/en/tracking",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Tracking",
    path: "/ar/tracking",
    isPrivate: false,
    exact: true,
  },
  {
    name: "PaymentSuccess",
    path: "/en/checkout/success",
    isPrivate: false,
    exact: true,
  },
  {
    name: "PaymentSuccess",
    path: "/ar/checkout/success",
    isPrivate: false,
    exact: true,
  },
  {
    name: "RegisterSuccess",
    path: "/en/register/success",
    isPrivate: false,
    exact: true,
  },
  {
    name: "RegisterSuccess",
    path: "/ar/register/success",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Order",
    path: "/en/order",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Order",
    path: "/ar/order",
    isPrivate: false,
    exact: true,
  },
  {
    name: "product-faqs",
    path: "/en/product-faqs",
    isPrivate: false,
    exact: true,
  },
  {
    name: "product-faqs",
    path: "/ar/product-faqs",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/en/products",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/ar/products",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/en/products/:id",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/ar/products/:id",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/en/products/:id/:sub",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Products",
    path: "/ar/products/:id/:sub",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Product",
    path: "/en/product/:id",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Product",
    path: "/ar/product/:id",
    isPrivate: false,
    exact: true,
  },
  {
    name: "About",
    path: "/en/about",
    isPrivate: false,
    exact: true,
  },
  {
    name: "About",
    path: "/ar/about",
    isPrivate: false,
    exact: true,
  },
  {
    name: "MotherBabyWorld",
    path: "/en/mother-baby-world",
    isPrivate: false,
    exact: true,
  },
  {
    name: "MotherBabyWorld",
    path: "/ar/mother-baby-world",
    isPrivate: false,
    exact: true,
  },
  {
    name: "GoodToKnow",
    path: "/en/good-to-know",
    isPrivate: false,
    exact: true,
  },
  {
    name: "GoodToKnow",
    path: "/ar/good-to-know",
    isPrivate: false,
    exact: true,
  },
  {
    name: "BreastFeedingAdvisor",
    path: "/en/breastfeeding-advisor",
    isPrivate: false,
    exact: true,
  },
  {
    name: "BreastFeedingAdvisor",
    path: "/ar/breastfeeding-advisor",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Blog",
    path: "/en/blog",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Blog",
    path: "/ar/blog",
    isPrivate: false,
    exact: true,
  },
  {
    name: "BlogDetailPage",
    path: "/en/blog/:id",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "BlogDetailPage",
    path: "/ar/blog/:id",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Video",
    path: "/en/video",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Video",
    path: "/ar/video",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Contact",
    path: "/en/contact",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Contact",
    path: "/ar/contact",
    isPrivate: false,
    exact: true,
  },
  {
    name: "FAQ",
    path: "/en/faq",
    isPrivate: false,
    exact: true,
  },
  {
    name: "FAQ",
    path: "/ar/faq",
    isPrivate: false,
    exact: true,
  },
  {
    name: "Wishlist",
    path: "/en/wishlist",
    isPrivate: true,
    exact: true,
    show: false,
  },
  {
    name: "Wishlist",
    path: "/ar/wishlist",
    isPrivate: true,
    exact: true,
    show: false,
  },
  {
    name: "Profile",
    path: "/en/profile",
    isPrivate: true,
    exact: true,
    show: false,
  },
  {
    name: "Profile",
    path: "/ar/profile",
    isPrivate: true,
    exact: true,
    show: false,
  },
  {
    name: "Pregnancy",
    path: "/en/stages-of-pregnancy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Pregnancy",
    path: "/ar/stages-of-pregnancy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Post Pregnancy",
    path: "/en/post-pregnancy-care",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Post Pregnancy",
    path: "/ar/post-pregnancy-care",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Baby Care",
    path: "/en/baby-care",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Baby Care",
    path: "/ar/baby-care",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "First Time Father",
    path: "/en/first-time-father",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "First Time Father",
    path: "/ar/first-time-father",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Article",
    path: "/en/breastfeeding-advisor/:category/:article",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Article",
    path: "/ar/breastfeeding-advisor/:category/:article",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Disclosure Policy",
    path: "/en/disclosure-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Disclosure Policy",
    path: "/ar/disclosure-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Policy on Privacy Protection",
    path: "/en/privacy-protection-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Policy on Privacy Protection",
    path: "/ar/privacy-protection-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Social Media Policy",
    path: "/en/social-media-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Social Media Policy",
    path: "/ar/social-media-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Term Of Use",
    path: "/en/term-of-use",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Term Of Use",
    path: "/ar/term-of-use",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Term Of Use",
    path: "/en/shipping-return-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Term Of Use",
    path: "/ar/shipping-return-policy",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Official Social Media List",
    path: "/en/official-social-media-list",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Official Social Media List",
    path: "/ar/official-social-media-list",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Subsidiaries",
    path: "/en/subsidiaries",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Subsidiaries",
    path: "/ar/subsidiaries",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Sitemap",
    path: "/en/sitemap",
    isPrivate: false,
    exact: true,
    show: false,
  },
  {
    name: "Sitemap",
    path: "/ar/sitemap",
    isPrivate: false,
    exact: true,
    show: false,
  },
];

export default (
  <Switch>
    {routes.map((route) => {
      return <Route path={route.path} key={route.path} />;
    })}
  </Switch>
);
